networks:
  public:
    name: smoke_test_app_public
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.44.0.0/16
services:
  scylla:
    image: scylladb/scylla
    ports:
      - "127.0.0.1:9042:9042"
    networks:
      public:
        ipv4_address: 172.44.0.2
    command: |
      --rpc-address 172.44.0.2
      --listen-address 172.44.0.2
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 2
      --memory 1G
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "scylla",
          "-e",
          "select * from system.local WHERE key='local'",
        ]
      interval: 5s
      timeout: 5s
      retries: 60
